### ISSUE TITLE
Error when using failed ticks

### ISSUE THREAD

**Issue by joeygallegos** [joeygallegos/PythonMonitorScript#4]
Error when running the command, seems like error when reading the tracking json file

```logs
do_heartbeat_check ended
Traceback (most recent call last):
  File "run.py", line 302, in <module>
    current_fail_ticks = get_failed_ticks()
  File "run.py", line 211, in get_failed_ticks
    current_json_tracking = json.loads(tracking_file.read())
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by joeygallegos** [comment]
```
----
starting heartbeat check for hernandezbrothers.com
checking endpoint / for a status code 200
checking endpoint /about for a status code 200
do_heartbeat_check ended
get object data from read_data_from_manifest()
replace entry with new count
opening tracking.json with w+
write tracking.json
close tracking.json
Checking if we need to set the incident start time
Sending an alert to emails
get_email_markup started
Traceback (most recent call last):
  File "run.py", line 328, in <module>
    get_pretty_time(datetime.fromisoformat(get_incident_start_timestamp())),
ValueError: Invalid isoformat string: ''
root@StardustCore01:/var/www/PythonMonitorScript#
```
